defaults: &defaults
  docker:
    - image: circleci/node:10

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download, install and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run tests!
      - run: yarn run test-ci

      - persist_to_workspace:
          root: .
          paths:
            - '*'

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
